# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.GearFrame = QtWidgets.QFrame(self.centralwidget)
        self.GearFrame.setGeometry(QtCore.QRect(30, 20, 371, 80))
        self.GearFrame.setStyleSheet("#GearFrame{\n"
"background-color:gray;\n"
"}\n"
"")
        self.GearFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.GearFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.GearFrame.setObjectName("GearFrame")
        self.Gear_D = QtWidgets.QRadioButton(self.GearFrame)
        self.Gear_D.setGeometry(QtCore.QRect(310, 30, 41, 24))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Gear_D.setFont(font)
        self.Gear_D.setObjectName("Gear_D")
        self.label = QtWidgets.QLabel(self.GearFrame)
        self.label.setGeometry(QtCore.QRect(10, 20, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Gear_P = QtWidgets.QRadioButton(self.GearFrame)
        self.Gear_P.setGeometry(QtCore.QRect(110, 30, 41, 24))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Gear_P.setFont(font)
        self.Gear_P.setObjectName("Gear_P")
        self.Gear_N = QtWidgets.QRadioButton(self.GearFrame)
        self.Gear_N.setGeometry(QtCore.QRect(240, 30, 41, 24))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Gear_N.setFont(font)
        self.Gear_N.setObjectName("Gear_N")
        self.Gear_R = QtWidgets.QRadioButton(self.GearFrame)
        self.Gear_R.setGeometry(QtCore.QRect(170, 30, 41, 24))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Gear_R.setFont(font)
        self.Gear_R.setObjectName("Gear_R")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(120, 200, 141, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Gear_D.setText(_translate("MainWindow", "D"))
        self.label.setText(_translate("MainWindow", "GEAR"))
        self.Gear_P.setText(_translate("MainWindow", "P"))
        self.Gear_N.setText(_translate("MainWindow", "N"))
        self.Gear_R.setText(_translate("MainWindow", "R"))
        self.pushButton.setText(_translate("MainWindow", "左上部分"))
